name: "List Unique Projects"
description: "List unique projects and count the number of issues associated with one or more projects"

inputs:
  github_token:
    description: "GitHub token"
    required: false
  github_app_id:
    description: "GitHub App ID"
    required: false
  github_private_key:
    description: "GitHub Private Key"
    required: false
  github_installation_id:
    description: "GitHub Installation ID"
    required: false
  api_url:
    description: "GitHub API URL"
    required: false
  repos_file:
    description: "Path to the file containing the list of repositories (one repo per line)"
    required: true
  org_name:
    description: "Organization name"
    required: true
  output_file:
    description: "Output CSV file name"
    required: false
    default: "output.csv"

runs:
  using: "node20"
  main: "index.js"

